from setuptools import find_packages, setup  # pragma: no cover

setup(  # pragma: no cover
    name="Scikit-longitudinal",
    version="0.1.8",
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url="https://github.com/simonprovost/scikit-longitudinal",
    description="Scikit-longitudinal is an open-source Python library for longitudinal data analysis, building on Scikit-learn's foundation with tools tailored for repeated measures data.",
    author="Provost Simon, Alex Freitas",
    author_email="simon.gilbert.provost@gmail.com, a.a.freitas@kent.ac.uk",
    packages=find_packages(),
    project_urls={
        'Homepage': 'https://github.com/simonprovost/scikit-longitudinal',
        'Documentation': 'https://scikit-longitudinal.readthedocs.io/latest/',
        'Releases': 'https://github.com/simonprovost/scikit-longitudinal/releases',
        'Repository': 'https://github.com/simonprovost/scikit-longitudinal',
        'Issues': 'https://github.com/simonprovost/scikit-longitudinal/issues/',
        'Scientific Paper': 'https://joss.theoj.org/papers/10.21105/joss.08481',
    },
    classifiers=[
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Programming Language :: Python :: 3.13',
    ],
    install_requires=[
        "scipy>=1.11.0,<2.0.0",
        "pandas>=2.2.0,<3.0.0",
        "matplotlib<4.0.0,>=3.8.0",
        "jupyter<2.0.0,>=1.0.0",
        "overrides<8.0.0,>=7.3.1",
        "statsmodels<1.0.0,>=0.14.0",
        "numpy>=1.26.4,<2.0.0",
        "graphviz<1.0.0,>=0.20.1",
        "liac-arff>=2.2.2",
        "threadpoolctl<4.0.0,>=3.1.0",
        "stopit>=1.1.2",
        "rich>=13.6.0",
        "joblib>=0.11",
        "deep-forest-py310>=0.1.9",
        "scikit-lexicographical-trees==0.0.4",
    ],
    extras_require={
        "dev": [
            "pytest>=4.4.0",
            "pytest-cov>=4.0.0",
            "black>=23.10.1",
            "isort>=5.12.0",
            "black>=24.10.0",
            "ruff>=0.9.1",
            "markdown-callouts>=0.4",
            "markdown-exec>=1.8",
            "mkdocs>=1.6.1",
            "mkdocstrings[python]>=0.25",
            "tomli>=2.0; python_version < '3.11'",
            "mkdocstrings-python>=1.16.10",
            "pymdown-extensions>=10.14.3",
            "zensical>=0.0.28",
        ],
        "parallelisation": ["ray>=2.40.0"],
    },
    python_requires=">=3.10,<3.14",
    license="MIT",
)
