#!/usr/bin/env fish

# Get list of changed files
echo "Getting list of changed files..."
set changed_files (git diff --name-only ORIG_HEAD HEAD)
echo "Changed files: $changed_files"

# Check if any of them are Python files
for file in $changed_files
    if string match -qr '\.py$' $file
        echo "Python files have changed, running tests..."
        make tests
        if test $status -ne 0
            echo "Tests must pass before push!"
            exit 1
        end
        break
    end
end
