name: Build Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'src/**/*.py'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'src/**/*.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - name: Create virtual environment
        run: uv venv
      - name: Install dependencies
        run: uv sync --dev
      - name: Build documentation
        run: uv run mkdocs build --site-dir site