name: ci-documentation
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Install uv & dependencies
        uses: astral-sh/setup-uv@v4
        with:
          version: "0.5.11"
          enable-cache: true
      - name: Sync documentation dependencies
        run: |
          uv sync --group doc
      - name: Deploy documentation
        run: |
          uv run mkdocs gh-deploy --force --remote-branch gh-pages